project_id = "cstkeblqqyjwlrbppucu"

[functions.send-prequalification-notification]
verify_jwt = false

[functions.send-agent-onboarding-notification]
verify_jwt = false

[functions.notify-lead]
verify_jwt = false

[functions.save-lead-progress]
verify_jwt = false

[functions.forward-to-ghl]
verify_jwt = false

[functions.ghl-optout-sync]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false